In [34]:
import numpy as np
import pandas as pd

In [35]:
np.random.seed(101)

In [36]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

we gave 5 letters and 4 letters respectively because we have 5 rows and 4 columns

In [37]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [38]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [39]:
type(df['W'])

pandas.core.series.Series

In [40]:
type(df)

pandas.core.frame.DataFrame

data frame is a bunch of series which share the same index

In [41]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

to extract a series from a df but ignore the above method.    ALWAYS USE THE BRACKET NOTATION!!!!!

In [42]:
df[["W","X","Y"]]

W         X         Y
A  2.706850  0.628133  0.907969
B  0.651118 -0.319318 -0.848077
C -2.018168  0.740122  0.528813
D  0.188695 -0.758872 -0.933237
E  0.190794  1.978757  2.605967

to extract a group of Columns we need to pass a list in the bracket notation so u  will be returned a data 

In [232]:
df["new"]=df["X"]+df["Y"]

In [233]:
df

W         X         Y         Z       new
Countries                                                  
SA         2.706850  0.628133  0.907969  0.503826  1.536102
IND        0.651118 -0.319318 -0.848077  0.605965 -1.167395
AU        -2.018168  0.740122  0.528813 -0.589001  1.268936
PAK        0.188695 -0.758872 -0.933237  0.955057 -1.692109

to add a new column one way is u can u can perfrom arithemetic operations

In [235]:
df.drop('new',axis=1)

W         X         Y         Z
Countries                                        
SA         2.706850  0.628133  0.907969  0.503826
IND        0.651118 -0.319318 -0.848077  0.605965
AU        -2.018168  0.740122  0.528813 -0.589001
PAK        0.188695 -0.758872 -0.933237  0.955057

if we have to remove a column we have df.drop but it is for rows if u want to remove columns u just have to specify axis=1

In [46]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  1.536102
B  0.651118 -0.319318 -0.848077  0.605965 -1.167395
C -2.018168  0.740122  0.528813 -0.589001  1.268936
D  0.188695 -0.758872 -0.933237  0.955057 -1.692109
E  0.190794  1.978757  2.605967  0.683509  4.584725

but as we see the the new column didnt dissappear this was bceacuse the drop method has inplace false so we have to set it to true

In [47]:
df.drop("new",axis=1,inplace=True)

In [48]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

now the column new has dissappeared

In [49]:
df.drop("E",axis=0,inplace=True)

In [50]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [51]:
df.shape

(4, 4)

In [52]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [53]:
df.loc["A"]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

to extract a row there are two methods one is the method given above

rows are series and columns are series too

In [54]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

the second method is indexing the rows i loc is indexed location(iguess)

In [55]:
df.iloc[2,3]

-0.5890005332865824

In [56]:
df.loc["C","Z"]

-0.5890005332865824

this is how we extract a particular value in dataframe

In [57]:
df.loc[["A","B"],["X","Y","Z"]]

X         Y         Z
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965

In [58]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [59]:
df>1

W      X      Y      Z
A   True  False  False  False
B  False  False  False  False
C  False  False  False  False
D  False  False  False  False

conditional selection

In [60]:
booldf=df>0

In [61]:
booldf

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True

In [62]:
type(booldf)

pandas.core.frame.DataFrame

In [63]:
df[booldf]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057

so first we apply the condition what we want and store it in a different data frame for example like booldf.after we get a df we pass that df which has boolean values to the dataframe ie df[booldataframe]

In [64]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057

the above operation can be done like this within one step

In [65]:
df["W">0]

TypeError: '>' not supported between instances of 'str' and 'int'

In [66]:
df["W"]>0

A     True
B     True
C    False
D     True
Name: W, dtype: bool

In [67]:
df[df["W"]>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

what the above function does is it filters the columns which are false and returns us only true columns

In [68]:
df[df["Z"]<0]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [71]:
resultdf=df[df["W"]>0]

In [72]:
resultdf

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [73]:
resultdf["X"]

A    0.628133
B   -0.319318
D   -0.758872
Name: X, dtype: float64

In [74]:
resultdf[resultdf["X"]>0]

W         X         Y         Z
A  2.70685  0.628133  0.907969  0.503826

In [236]:
df

W         X         Y         Z       new
Countries                                                  
SA         2.706850  0.628133  0.907969  0.503826  1.536102
IND        0.651118 -0.319318 -0.848077  0.605965 -1.167395
AU        -2.018168  0.740122  0.528813 -0.589001  1.268936
PAK        0.188695 -0.758872 -0.933237  0.955057 -1.692109

In [237]:
df.index.names

FrozenList(['Countries'])

In [76]:
df[df["X"]>0]["X"]

A    0.628133
C    0.740122
Name: X, dtype: float64

In [77]:
df[df["X"]>0].loc[["A"],["Y"]]

Y
A  0.907969

In [78]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

conditionals in dataframes

In [80]:
df[df["W"]>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [82]:
df[("W">0 and "Y">0)]

TypeError: '>' not supported between instances of 'str' and 'int'

In [87]:
(df["W"]>0) & (df["Y"]>0)

A     True
B    False
C    False
D    False
dtype: bool

In [88]:
 df[(df["W"]>0)&(df["Y"]>0)]

W         X         Y         Z
A  2.70685  0.628133  0.907969  0.503826

reset the index

In [89]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057

In [90]:
df["X"]

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
Name: X, dtype: float64

In [100]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [106]:
ind='SA IND AU PAK' .split(" ")

In [107]:
ind

['SA', 'IND', 'AU', 'PAK']

In [110]:
df["Countries"]=ind

In [114]:
df.drop("countries",inplace=True,axis=1)

In [115]:
df

W         X         Y         Z Countries
A  2.706850  0.628133  0.907969  0.503826        SA
B  0.651118 -0.319318 -0.848077  0.605965       IND
C -2.018168  0.740122  0.528813 -0.589001        AU
D  0.188695 -0.758872 -0.933237  0.955057       PAK

In [120]:
df

W         X         Y         Z
Countries                                        
SA         2.706850  0.628133  0.907969  0.503826
IND        0.651118 -0.319318 -0.848077  0.605965
AU        -2.018168  0.740122  0.528813 -0.589001
PAK        0.188695 -0.758872 -0.933237  0.955057

In [121]:
df.loc["SA"]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: SA, dtype: float64

to set a existing column as a index we have to use the method df.set_index("name of the column")

In [222]:
d2=np.arange(0,18)


In [223]:
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [224]:
d2=d2.reshape(6,3)

In [225]:
d2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [173]:
col1= "A B C".split(" ")

In [174]:
col1

['A', 'B', 'C']

In [175]:
row1="F G H".split(" ")

In [176]:
row1

['F', 'G', 'H']

In [177]:
df2=pd.DataFrame(d2,row1,col1)

In [170]:
d3=np.random.randn(5,4)

In [171]:
d3

array([[-9.93263500e-01,  1.96799505e-01, -1.13664459e+00,
         3.66479606e-04],
       [ 1.02598415e+00, -1.56597904e-01, -3.15791439e-02,
         6.49825833e-01],
       [ 2.15484644e+00, -6.10258856e-01, -7.55325340e-01,
        -3.46418504e-01],
       [ 1.47026771e-01, -4.79448039e-01,  5.58769406e-01,
         1.02481028e+00],
       [-9.25874259e-01,  1.86286414e+00, -1.13381716e+00,
         6.10477908e-01]])

In [178]:
df2

A  B  C
F  0  1  2
G  3  4  5
H  6  7  8

In [179]:
df

W         X         Y         Z
Countries                                        
SA         2.706850  0.628133  0.907969  0.503826
IND        0.651118 -0.319318 -0.848077  0.605965
AU        -2.018168  0.740122  0.528813 -0.589001
PAK        0.188695 -0.758872 -0.933237  0.955057

dataframes 3

In [211]:
outside="hello hello hello hi hi hi".split(" ")

In [212]:
inside="1 2 3 1 2 3".split(" ")

In [213]:
outside

['hello', 'hello', 'hello', 'hi', 'hi', 'hi']

In [214]:
inside

['1', '2', '3', '1', '2', '3']

In [215]:
hier_index=list(zip(outside,inside))

zip function is for making two lists combined into a list of tuples based upon the index

In [216]:
hier_index

[('hello', '1'),
 ('hello', '2'),
 ('hello', '3'),
 ('hi', '1'),
 ('hi', '2'),
 ('hi', '3')]

In [217]:
hier_index1=pd.MultiIndex.from_tuples(hier_index)

In [218]:
hier_index1

MultiIndex(levels=[['hello', 'hi'], ['1', '2', '3']],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [229]:
df3=pd.DataFrame(d2,hier_index1,["S","T","U"])

In [227]:
df3

S   T   U
hello 1   0   1   2
      2   3   4   5
      3   6   7   8
hi    1   9  10  11
      2  12  13  14
      3  15  16  17

this is for combining or making a outer and inner index 
wont be that useful

In [231]:
df3.loc["hello"].loc["1"]

S    0
T    1
U    2
Name: 1, dtype: int32

In [238]:
df3.index.names=["greetings","S.no"]

In [239]:
df3

S   T   U
greetings S.no            
hello     1      0   1   2
          2      3   4   5
          3      6   7   8
hi        1      9  10  11
          2     12  13  14
          3     15  16  17

In [240]:
df3.loc["hello"]

S  T  U
S.no         
1     0  1  2
2     3  4  5
3     6  7  8

In [243]:
df3.loc["hello"].loc["1"]["S"]

0

In [245]:
df3.xs("hello")

S  T  U
S.no         
1     0  1  2
2     3  4  5
3     6  7  8